apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-uwtx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-uwtx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-uwtx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-uwtx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-uwtx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dmkd-tenant/rhtap-demo-app/hacbs-test-project-uwtx@sha256:1f6edf1f5871dacc406ce4af8414a77f27e2dee58b544ad12af4d587d7e4e6de
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
